### ISSUE TITLE
Facilitar el  agregar a una organización

### ISSUE THREAD

**Issue by renich** [LinuxCabal/dir-foss#12]
Es necesario usar un método para agregar organizaciones; acompañado de una plantilla y que haga fácil el llenado.

A lo mejor una orden a make para que cree una plantilla?

Sería bueno incluir alguna pruebita para no permitir plantillas vacías.

**Comment by alvarezp** [comment]
No se podría con Make porque no soporta parámetros (como el nombre para ponerle al nuevo archivo). Tendría que ser un script, pero yo creo que no es necesario tal script si en el `README.md` se documenta el procedimiento. Tal procedimiento podría ser simplemente:
1. Toma la plantilla en `plantillas/gulnew.yaml` y cópiala a `src/`
2. Modifica el archivo.

Para `plantillas/gulnew.yaml` podría ser el siguiente contenido:

```
---
nombre: Grupo de Usuarios de ...
activo: false
acronimo: gulnew
comentario: Grupo nuevo
direccion:
    ciudad: Ciudad
    estado: Estado
contacto:
    e-mail: contacto@example.com
presencia:
    facebook: https://www.facebook.com/groups/gulnew
    github: https://github.com/gulnew
    google-groups:
        - informacion: https://groups.google.com/forum/#!forum/gulnew-anuncios
          tema: Anuncios
        - informacion: https://groups.google.com/forum/#!forum/gulnew
          e-mail: gulnew@example.com
          tema: General
    google-plus: https://plus.google.com/communities/123456789123456789123
    irc: irc://freenode.net/#gulnew
    planeta: http://www.gulnew.org/planet
    podcast:
        - nombre: Podcast de Gulnew
          activo: false
          formatos:
              - mp3: http://podcast.gulnew.org/mp3
              - vorbis: http://podcast.gulnew.org/ogg
    twitter: https://twitter.com/gulnew
    web: http://www.gulnew.org/
```

Y, sí, con esta plantilla podría haber un test para encontrar archivos que contengan cadenas por defecto y fallar la prueba. Algo basado en `! [ -f src/gulnew.yaml ] && ! egrep 'Usuarios de \.\.\.$|gulnew|example\.com|123456789' src/*.yaml`
